# Generated by Django 2.0.4 on 2018-05-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Site'),
        ),
        migrations.AlterField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=127),
        ),
    ]
