# Generated by Django 2.0.5 on 2018-05-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='added_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
