# Generated by Django 2.0.6 on 2018-06-24 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_link_added_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='added_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
