# Generated by Django 2.0.4 on 2018-05-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180502_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='link_num',
        ),
        migrations.AddField(
            model_name='link',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='site',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
