# Generated by Django 2.0.4 on 2018-05-01 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('posts', '0001_initial'), ('posts', '0002_remove_link_desc'), ('posts', '0003_auto_20180502_0115'), ('posts', '0004_auto_20180502_0116'), ('posts', '0005_auto_20180502_0116')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('content', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=127)),
                ('link_num', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Site'),
        ),
    ]
