# Generated by Django 2.0.4 on 2018-04-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='desc',
        ),
    ]
