# Generated by Django 2.0.4 on 2018-05-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20180502_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Site'),
        ),
    ]
